import { Token, DiceRollResult } from './tokens';

/**
 * Takes a list of Tokens from the tokenize function and processes them.
 * @param tokens the list of tokens generated by the tokenize function
 */
function processTokens(tokens: Token[]): DiceRollResult {
  return {
    value: 0,
    tokens: [],
  };
}

export default processTokens;
